---

# Cluster Configurations
cluster_name: ''
cluster_type: 'poc' # (poc|rhpds|dev)
cluster_provisioning_vars_inventory: "{{ cluster_name }}"
cluster_aws_region: ''
cluster_aws_access_key: ''
cluster_aws_secret_access_key: ''

# Integreatly
integreatly_version: 'release-1.4.0'

# Workflow Job Template
integreatly_workflow_install_job_template_name: 'Integreatly Install Workflow'
integreatly_workflow_install_job_template_desc: 'Workflow for Installing Integreatly on Openshift'
integreatly_workflow_install_job_template_organization: "{{ tower_organization }}"

integreatly_workflow_uninstall_job_template_name: 'Integreatly Uninstall Workflow'
integreatly_workflow_uninstall_job_template_desc: 'Workflow for Uninstalling Integreatly on Openshift'
integreatly_workflow_uninstall_job_template_organization: "{{ tower_organization }}"

# Integreatly Credentials
integreatly_credential_bundle_github_name: "tower_github_scm"
integreatly_credential_bundle_github_desc: "SCM credentials for Integreatly project"
integreatly_credential_bundle_github_kind: 'scm'

# Integreatly Job Templates: Install
integreatly_job_template_bootstrap_install_name: 'Integreatly Bootstrap Install Template'
integreatly_job_template_bootstrap_install_desc: 'Job for bootstrapping integreatly cluster resources'
integreatly_job_template_bootstrap_install_type: 'run'
integreatly_job_template_bootstrap_install_playbook: 'playbooks/bootstrap_integreatly_install.yml'
integreatly_job_template_bootstrap_install_credentials: "{{ tower_credential_bundle_default_name }}"

integreatly_job_template_deploy_name: 'Integreatly Deploy Template'
integreatly_job_template_deploy_desc: 'Job for deploying Integreatly on Openshift'
integreatly_job_template_deploy_type: 'run'
integreatly_job_template_deploy_playbook: 'playbooks/install.yml'
integreatly_job_template_deploy_credentials: "{{ tower_credential_bundle_default_name }}"

# Integreatly Job Templates: Uninstall
integreatly_job_template_uninstall_name: 'Integreatly Uninstall Template'
integreatly_job_template_uninstall_desc: 'Job for uninstalling Integreatly on Openshift'
integreatly_job_template_uninstall_type: 'run'
integreatly_job_template_uninstall_playbook: 'playbooks/uninstall.yml'
integreatly_job_template_uninstall_credentials: "{{ tower_credential_bundle_default_name }}"

integreatly_job_template_bootstrap_uninstall_name: 'Integreatly Bootstrap Uninstall Template'
integreatly_job_template_bootstrap_uninstall_desc: 'Job for bootstrapping resources for Integreatly uninstall'
integreatly_job_template_bootstrap_uninstall_type: 'run'
integreatly_job_template_bootstrap_uninstall_playbook: 'playbooks/bootstrap_integreatly_uninstall.yml'
integreatly_job_template_bootstrap_uninstall_credentials: "{{ tower_credential_bundle_default_name }}"

integreatly_job_template_cleandown_name: 'Integreatly Clean Down Template'
integreatly_job_template_cleandown_desc: 'Job for cleaning down Integreatly resources'
integreatly_job_template_cleandown_type: 'run'
integreatly_job_template_cleandown_playbook: 'playbooks/bootstrap_integreatly_cleandown.yml'
integreatly_job_template_cleandown_credentials: "{{ tower_credential_bundle_default_name }}"

# Integreatly Projects
integreatly_project_install_scm_branch: ''
integreatly_project_install_name: "integreatly-install-{{ integreatly_project_install_scm_branch }}"
integreatly_project_install_desc: "Integreatly Project for Branch: {{ integreatly_project_install_scm_branch }}"
integreatly_project_install_scm_type: git
integreatly_project_install_scm_clean: true
integreatly_project_install_scm_url: ''
integreatly_project_install_scm_update_on_launch: true
integreatly_project_install_scm_delete_on_update: true

integreatly_project_uninstall_scm_branch: ''
integreatly_project_uninstall_name: "integreatly-uninstall-{{ integreatly_project_uninstall_scm_branch }}"
integreatly_project_uninstall_desc: "Integreatly Project for Branch: {{ integreatly_project_uninstall_scm_branch }}"
integreatly_project_uninstall_scm_type: git
integreatly_project_uninstall_scm_clean: true
integreatly_project_uninstall_scm_url: ''
integreatly_project_uninstall_scm_update_on_launch: true
integreatly_project_uninstall_scm_delete_on_update: true

# Integreatly Inventories
integreatly_inventory_name: "{{ cluster_name }}"
integreatly_inventory_desc: "Integreatly Inventory: {{ cluster_name }}"

# Integreatly Sources
integreatly_inventory_source_aws_name: "{{ cluster_name }}-inventory-source-aws"
integreatly_inventory_source_aws_type: 'ec2'
integreatly_inventory_source_aws_update_on_launch: false
integreatly_inventory_source_aws_overwrite: false
integreatly_inventory_source_aws_credentials: ''
integreatly_inventory_source_aws_regions: 'All'
integreatly_inventory_source_aws_instance_filters: "tag:clusterid={{ cluster_name }}"

integreatly_inventory_source_project_name: "{{ cluster_name }}-inventory-source-project-{{ integreatly_project_install_name }}"
integreatly_inventory_source_project_type: 'scm'
integreatly_inventory_source_project_path: "inventories/"
integreatly_inventory_source_project_update_on_launch: false
integreatly_inventory_source_project_overwrite: false
integreatly_inventory_source_project_overwrite_vars: false

# Integreatly Groups
integreatly_group_master_name: 'master'
integreatly_group_master_desc: "Master group: {{ cluster_name }}"
integreatly_group_master_overwrite: true
integreatly_group_master_overwrite_vars: true
integreatly_group_master_update_on_launch: false
integreatly_group_master_aws_name: 'tag_host_type_master'

integreatly_group_local_name: 'local'
integreatly_group_local_desc: "Local group: {{ cluster_name }}"
integreatly_group_local_overwrite: true
integreatly_group_local_overwrite_vars: true
integreatly_group_local_update_on_launch: false

# Integreatly Hosts
integreatly_host_local_name: 'localhost'
integreatly_host_local_desc: "Localhost: {{ cluster_name }}"

# Integreatly Survey
integreatly_install_survey_aws_accounts: []

# OSD install
integreatly_osd_install_branch: 'release-1.3.0'
integreatly_osd_project_install_scm_url: "git@github.com:integr8ly/installation.git"
integreatly_osd_install_desc: "Integreatly Project: {{ integreatly_osd_install_branch }}"
integreatly_osd_install_org: integreatly
integreatly_osd_install_inventory: OSD_Tower_Inventory
integreatly_osd_install_source_name:  installation-project-source
integreatly_osd_install_source_path: "inventories/"
integreatly_osd_install_name: "Integreatly_Install_Template_[OSD]"
integreatly_osd_bootstrap_name: "Integreatly_Bootstrap_Template_[OSD]"
integreatly_osd_workflow_name: "Integreatly_Bootstrap_and_Install_[OSD]"
integreatly_osd_workflow_description: "Workflow to configure and install integreatly on an OSD cluster"
integreatly_osd_source_project_update_on_launch: true