---

- name: "Configure Cluster Bootstrap job template: {{ integreatly_job_template_bootstrap_install_name }}"
  tower_job_template:
    name: "{{ integreatly_job_template_bootstrap_install_name }}"
    description: "{{ integreatly_job_template_bootstrap_install_desc }}"
    job_type: "{{ integreatly_job_template_bootstrap_install_type }}"
    playbook: "{{ integreatly_job_template_bootstrap_install_playbook }}"
    project: "{{ tower_configuration_project_name }}"
    credential: "{{ integreatly_job_template_bootstrap_install_credentials }}"
    state: present
    inventory: "{{ tower_inventory_name }}"
    tower_verify_ssl: '{{ tower_verify_ssl }}'
    extra_vars_path: '{{ tower_extra_vars_file_path }}'

- name: "Configure Integreatly Deploy job template: {{ integreatly_job_template_deploy_name }}"
  tower_job_template:
    name: "{{ integreatly_job_template_deploy_name }}"
    description: "{{ integreatly_job_template_deploy_desc }}"
    job_type: "{{ integreatly_job_template_deploy_type }}"
    playbook: "{{ integreatly_job_template_bootstrap_install_playbook }}"
    project: "{{ tower_configuration_project_name }}"
    credential: "{{ integreatly_job_template_deploy_credentials }}"
    state: present
    inventory: "{{ tower_inventory_name }}"
    vault_credential: "{{ tower_credential_bundle_vault_name }}"
    tower_verify_ssl: '{{ tower_verify_ssl }}'

- name: Retrieve AWS Credential Type ID
  shell: "tower-cli credential_type list --kind cloud -n \"Amazon Web Services\" -f id"
  register: aws_cred_type_id

- name: Retrieve list of AWS Credential Bundles
  shell: "tower-cli credential list --credential-type {{ aws_cred_type_id.stdout }} -f json"
  register: aws_credentials_raw

- set_fact:
    aws_credentials_json: "{{ aws_credentials_raw.stdout | from_json }}"
    integreatly_aws_accounts: []

- name: "Set list of Integreatly AWS Accounts"
  set_fact:
    integreatly_aws_accounts: "{{ integreatly_aws_accounts + [ item.name ] }}"
  with_items: "{{ aws_credentials_json.results }}"
  no_log: true

- set_fact:
    integreatly_install_survey_aws_accounts: "{{ integreatly_aws_accounts | join('\\n')}}"

- name: "Create workflow: {{ integreatly_workflow_install_job_template_name }}"
  tower_workflow_template:
    name:  "{{ integreatly_workflow_install_job_template_name }}"
    description: "{{ integreatly_workflow_install_job_template_desc }}"
    state: present
    organization: "{{ integreatly_workflow_install_job_template_organization }}"
    tower_verify_ssl: '{{ tower_verify_ssl }}'
  register: create_workflow_response

- name: Create install workflow schema
  template:
    src: workflow_install_schema.yml.j2
    dest: "/tmp/workflow_install_schema.yml"

- name: Create install workflow survey
  template:
    src: workflow_install_survey.json.j2
    dest: "/tmp/workflow_install_survey.json"

- name: Update install workflow job template with survey
  shell: "tower-cli workflow modify --name=\"{{ integreatly_workflow_install_job_template_name }}\" --survey-enabled=true --survey-spec='@/tmp/workflow_install_survey.json' --extra-vars='@{{ tower_extra_vars_file_path }}'"

- name: Update install workflow job template with schema
  shell: "tower-cli workflow schema \"{{ integreatly_workflow_install_job_template_name }}\" @/tmp/workflow_install_schema.yml"

# Update the workflow to enable ask_variables_on_launch via the tower api
- include_role:
    name: tower
    tasks_from: enable_ask_variables_on_launch.yml
  vars:
    workflow_id: "{{ create_workflow_response.id }}"
    
- name: Cleanup temp install workflow files
  file:
    path: "{{ item }}"
  with_items:
    - /tmp/workflow_install_schema.yml
    - /tmp/workflow_install_survey.json