---
- name: Copy the tower_github_scm key to server.
  copy:
    content: '{{ tower_github_scm }}'
    dest: '/home/{{ cluster_credential_git_user }}/.ssh/tower_github_scm'
    mode: 0600
    owner: '{{ cluster_credential_git_user }}'
    group: '{{ cluster_credential_git_user_group }}'
- name: Clone the credential repo
  git:
    repo: '{{ cluster_credential_git_repo }}'
    version: '{{ cluster_credential_git_ref }}'
    dest: /tmp/credential_repo
    accept_hostkey: yes
    key_file: '/home/{{ cluster_credential_git_user }}/.ssh/tower_github_scm'
