---
# Ansible Tower Configurations
tower_login: true
tower_host: ''
tower_username: ''
tower_password: ''
tower_verify_ssl: false

# Ansible Tower Openshift Configurations
tower_openshift_username: ''
tower_openshift_password: ''
tower_openshift_master_url: ''
tower_openshift_login: true

# Ansible Tower Organizations
tower_organization: 'integreatly'
tower_secret_organization: 'secret'
tower_team: 'integreatly-eng'

# Ansible Tower Credentials
tower_credential_bundle_vault_name: 'integreatly_vault'
tower_credential_bundle_vault_desc: 'Default Tower vault credential'
tower_credential_bundle_vault_type: 'vault'

tower_credential_bundle_default_name: 'tower_provisioner'
tower_credential_bundle_default_desc: 'Default Tower machine credential'
tower_credential_bundle_default_type: 'ssh'

tower_credential_bundle_github_name: "tower_github_scm"
tower_credential_bundle_github_desc: "Default Tower Credential Bundle for Github"
tower_credential_bundle_github_type: 'scm'

tower_credential_bundle_aws_type: "aws"
aws_credential_list: []

# Ansible Tower Default Inventories
tower_inventory_name: 'Default Tower Inventory'
tower_inventory_desc: 'Default Tower Inventory used for local jobs'

# Ansible Tower Configurations Projects
tower_configuration_project_name: 'Ansible Tower Configuration Project'
tower_configuration_project_desc: 'Configuration project for Ansible Tower'
tower_configuration_project_scm_type: git
tower_configuration_project_scm_branch: 'master'
tower_configuration_project_scm_clean: true
tower_configuration_project_scm_type_url: 'https://github.com/integr8ly/ansible-tower-configuration.git'
tower_configuration_project_scm_update_on_launch: true
tower_configuration_project_scm_delete_on_update: true

# Ansible Tower Credential Projects
tower_credentials_project_name: 'Ansible Tower Credentials Project'
tower_credentials_project_desc: 'Credentials project for Ansible Tower'
tower_credentials_project_scm_type: git
tower_credentials_project_scm_branch: 'master'
tower_credentials_project_scm_clean: true
tower_credentials_project_scm_type_url: ''
tower_credentials_project_scm_update_on_launch: true
tower_credentials_project_scm_delete_on_update: true

# Ansible Tower Job Templates
tower_job_template_authenticate_tower_name: 'Ansible Tower Authenticate'
tower_job_template_authenticate_tower_desc: 'Job Template for Authenticating against Tower'
tower_job_template_authenticate_tower_job_type: 'run'
tower_job_template_authenticate_tower_job_playbook: 'playbooks/authenticate_tower.yml'
tower_job_template_authenticate_tower_job_credentials: "{{ tower_credential_bundle_default_name }}"

tower_job_template_authenticate_openshift_name: 'Openshift Authenticate'
tower_job_template_authenticate_openshift_desc: 'Job Template for Authenticating against Openshift'
tower_job_template_authenticate_openshift_job_type: 'run'
tower_job_template_authenticate_openshift_job_playbook: 'playbooks/authenticate_openshift.yml'
tower_job_template_authenticate_openshift_job_credentials: "{{ tower_credential_bundle_default_name }}"

# Ansible Tower Hosts
tower_host_local_name: 'local'
tower_host_local_desc: ""

