---
# Ansible Tower Configurations
tower_login: true
tower_environment: "{{ lookup('env','tower_environment')}}"
tower_host: '{{ lookup("vars", "_".join((tower_environment, "tower_host")) ) }}'
tower_username: '{{ lookup("vars", "_".join((tower_environment, "tower_username")) ) }}'
tower_password: '{{ lookup("vars", "_".join((tower_environment, "tower_password")) ) }}'
tower_verify_ssl: '{{ lookup("vars", "_".join((tower_environment, "tower_verify_ssl")) ) }}'

# Ansible Tower Openshift Configurations
tower_openshift_username: ''
tower_openshift_password: ''
tower_openshift_master_url: ''
tower_openshift_project: 'tower'
tower_openshift_login: true

# Ansible Tower Organizations
tower_organization: 'integreatly'
tower_secret_organization: 'secret'
tower_team: 'integreatly-eng'

# Ansible Tower Credentials
tower_credential_bundle_vault_name: 'integreatly_vault'
tower_credential_bundle_vault_desc: 'Default Tower vault credential'
tower_credential_bundle_vault_type: 'vault'

tower_credential_bundle_default_name: 'tower_provisioner'
tower_credential_bundle_default_desc: 'Default Tower machine credential'
tower_credential_bundle_default_type: 'ssh'

tower_credential_bundle_github_name: "tower_github_scm"
tower_credential_bundle_github_desc: "Default Tower Credential Bundle for Github"
tower_credential_bundle_github_type: 'scm'

tower_credential_bundle_aws_type: "aws"
aws_credential_list: []

# Ansible Tower Default Inventories
tower_inventory_name: 'Default Tower Inventory'
tower_inventory_desc: 'Default Tower Inventory used for local jobs'

# Ansible Tower Configurations Projects
tower_configuration_project_name: 'Ansible Tower Configuration Project'
tower_configuration_project_desc: 'Configuration project for Ansible Tower'
tower_configuration_project_scm_type: git
tower_configuration_project_scm_branch: 'master'
tower_configuration_project_scm_clean: true
tower_configuration_project_scm_type_url: 'https://github.com/integr8ly/ansible-tower-configuration.git'
tower_configuration_project_scm_update_on_launch: true
tower_configuration_project_scm_delete_on_update: true

# Ansible Tower Credential Projects
tower_credentials_project_name: 'Ansible Tower Credentials Project'
tower_credentials_project_desc: 'Credentials project for Ansible Tower'
tower_credentials_project_scm_type: git
tower_credentials_project_scm_branch: 'master'
tower_credentials_project_scm_clean: true
tower_credentials_project_scm_type_url: ''
tower_credentials_project_scm_update_on_launch: true
tower_credentials_project_scm_delete_on_update: true

# Ansible Tower Job Templates
tower_job_template_authenticate_tower_name: 'Ansible Tower Authenticate'
tower_job_template_authenticate_tower_desc: 'Job Template for Authenticating against Tower'
tower_job_template_authenticate_tower_job_type: 'run'
tower_job_template_authenticate_tower_job_playbook: 'playbooks/authenticate_tower.yml'
tower_job_template_authenticate_tower_job_credentials: "{{ tower_credential_bundle_default_name }}"

tower_job_template_authenticate_openshift_name: 'Openshift Authenticate'
tower_job_template_authenticate_openshift_desc: 'Job Template for Authenticating against Openshift'
tower_job_template_authenticate_openshift_job_type: 'run'
tower_job_template_authenticate_openshift_job_playbook: 'playbooks/authenticate_openshift.yml'
tower_job_template_authenticate_openshift_job_credentials: "{{ tower_credential_bundle_default_name }}"

# Ansible Tower Hosts
tower_host_local_name: 'local'
tower_host_local_desc: ''

# Ansible Tower Installation Configurations
tower_version: '3.4.3'
tower_install_dir: "/tmp/ansible-tower-openshift-setup-{{ tower_version }}"
tower_archive_filename: "ansible-tower-openshift-setup-{{ tower_version }}.tar.gz"
tower_archive_url: "https://releases.ansible.com/ansible-tower/setup_openshift/{{ tower_archive_filename }}"

tower_kubernetes_task_version: 'latest'
tower_kubernetes_web_version: 'latest' 

tower_kubernetes_base_path: "{{ local_base_config_path|default('/tmp') }}/{{ tower_kubernetes_deployment_name }}-config"
tower_kubernetes_task_image: quay.io/integreatly/ansible-tower-container
tower_kubernetes_web_image: quay.io/integreatly/ansible-tower-container

tower_openshift_skip_tls_verify: true
tower_openshift_pg_emptydir: true

tower_dockerhub_base: ansible
tower_create_preload_data: True
tower_admin_user: admin
tower_admin_password: CHANGEME
tower_admin_email: 'root@localhost'

tower_rabbitmq_user: 'awx'
tower_rabbitmq_password: CHANGEME
tower_rabbitmq_erlang_cookie: cookiemonster_integreatly_77

tower_web_mem_request: 2
tower_web_cpu_request: 1500
tower_task_mem_request: 2
tower_task_cpu_request: 1500
tower_rabbitmq_mem_request: 2
tower_rabbitmq_cpu_request: 500
tower_memcached_mem_request: 1
tower_memcached_cpu_request: 500

tower_kubernetes_rabbitmq_version: "3.7.4"
tower_kubernetes_rabbitmq_image: "ansible/awx_rabbitmq"

tower_kubernetes_deployment_name: ansible-tower
tower_kubernetes_deployment_replica_size: 1

tower_awx_task_hostname: awx
tower_awx_web_hostname: awxweb
tower_postgres_data_dir: /tmp/pgdocker
tower_host_port: 80

tower_pg_username: awx
tower_pg_password: CHANGEME
tower_pg_database: awx
tower_pg_port: 5432

tower_docker_compose_dir: /var/lib/awx
tower_openshift_pg_pvc_name: postgresql

tower_default_cpu: 1500m
tower_default_memory: 2Gi

tower_secret_key: CHANGEME

tower_limit_range_name: "{{ tower_openshift_project }}-core-resource-limits"

