---
- hosts: localhost
  gather_facts: no
  tasks:
    - include_vars:
        ./roles/tower/defaults/main.yml
    - include_role:
        name: cluster
        tasks_from: cluster_teardown_post_teardown.yml