---
- import_playbook: "./authenticate_tower.yml"

- hosts: localhost
  gather_facts: no
  tasks:
    - include_vars:
        ./roles/tower/defaults/main.yml
    - include_role:
        name: cluster
        tasks_from: provision_cluster.yml